name: Test AWS

on:
  workflow_dispatch 

jobs:
  # Deploy to AWS 
  Deploy:
    runs-on: ubuntu-latest
    env:
      VAULT_PASS: ${{ secrets.VAULT_PASS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2.4.0
      with:
        token: ${{ secrets.TOKEN_WORKFLOW }}

    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.7' 

    - name: Install Ansible
      run: pip3 install boto boto3 ansible==4 ansible-vault

    - name: Prepare ssh key and vault password
      run: |
        echo "$VAULT_PASS" > vault_pass.txt
        echo "$SSH_KEY" > devops.pem
        chmod 400 vault_pass.txt
        chmod 400 devops.pem
        ssh-keygen -p -f devops.pem -m pem

    - name: test
      run: ll -r ./*

    - name: Run Ansible
      run: sudo ansible-playbook ansible/ec2.deploy.yml --user ec2-user --key-file devops.pem --e @ansible/group_vars/all/aws.yml --vault-password-file vault_pass.txt

          
